---

 - name: Gather package facts
   package_facts:
     manager: "auto"

 - name: Check if chrony is installed
   debug:
     msg: "Chrony found"
   when: "'chrony' in ansible_facts.packages"
   notify: disable chrony

 - name: Install ntpd
   yum:
     name: ntp
     state: installed

 - name: Configure ntpd
   template:
     src: ntp.conf
     dest: /etc/ntp.conf
   notify:
   - restart ntpd

 - name: Start and enable ntpd
   service:
     name: ntpd
     enabled: yes
     state: started

 - name: Install Cockpit packages
   yum:
     name: [cockpit, cockpit-packagekit, cockpit-storaged]
     state: installed

 - name: Ensure Firewalld is installed and running
   yum:
     name: firewalld
     state: installed
   notify: enable firewalld

 - name: Open Firewall
   firewalld:
     service: cockpit
     permanent: yes
     state: enabled

 - name: Start Cockpit socket
   service:
     name: cockpit.socket
     enabled: yes
     state: started

