---

- name: Install Cockpit packages
  yum:
    name: [cockpit, cockpit-packagekit, cockpit-storaged]
    state: installed

- name: Ensure Firewalld is installed and running
  yum:
    name: firewalld
    state: installed
  notify: enable firewalld

- name: Open Firewall
  firewalld:
    service: cockpit
    permanent: yes
    state: enabled

- name: Generate Openssl private key
  openssl_privatekey:
    path: /etc/pki/tls/private/cockpit.key

- name: Create new IPA Cockpit service
  ipa_service:
    name: cockpit/{{ ansible_fqdn }}
    state: present
    ipa_host: ipa.home.joalon.se
    ipa_user: admin
    # ipa_pass: topsecret

- name: Track Cockpit TLS certificate
  command:
    cmd: 'ipa-getcert request
      -f /etc/cockpit/ws-certs.d/10-ipa.cert
      -k /etc/pki/tls/private/cockpit.key
      --principal cockpit/"{{ ansible_fqdn }}"
      -C "cat /etc/pki/tls/private/cockpit.key >> /etc/cockpit/ws-certs.d/10-ipa.cert"'
    creates: /etc/cockpit/ws-certs.d/10-ipa.cert

- name: Start Cockpit socket
  service:
    name: cockpit.socket
    enabled: yes
    state: started
